### ISSUE TITLE
social buttons

### ISSUE THREAD

**Issue by rpk0** [rpk0/rpk_site#34]
vag, sto photo essays spaei to style ton buttons giati mpike mesa sto `<div class="inner-center">`
sta blog posts omos paizei kanonika.. 

branch: `more_social`

**Comment by srekoble** [comment]
θα το δω τώρα σε λίγο ;)

**Comment by rpk0** [comment]
check `_layouts/photo_post` and `_layouts/post_layout`

**Comment by rpk0** [comment]
thanks fellow collaborator you are awesome! :beer:
